# Generated by Django 2.2.8 on 2019-12-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191207_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='item',
            new_name='items',
        ),
    ]
